import type { Metadata } from "next";
import { ProgressBar, ProgressBarProvider } from "react-transition-progress";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Suspense } from "react";
import Loader from "@/components/ui/loader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ProgressBarProvider>
            <Suspense fallback={<Loader />}>
              {children}
              <ProgressBar className=" bg-primary fixed h-2 bottom-1 z-50" />
            </Suspense>
          </ProgressBarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
